# install hive
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]

# start hive
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

# stop hive
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]
