- name: Run metastore and hiveserver2 script
  shell: '. ~/.bash_profile; {{ item }}'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
  run_once: true
  with_items:
  - hive --service metastore -p {{ hive_metastore_port }} &
  - hive --service hiveserver2 &
