- name: kill metastore and hiveserver2 server
  shell: '. ~/.bash_profile; export HIVE_HOME={{ hive_home }}; {{ item }}'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
  run_once: true
  with_items:
  - ps -ef | grep java | grep {{ hive_version }} | grep HiveServer | awk '{print $2}' | xargs kill 2>/dev/null
  - ps -ef | grep java | grep {{ hive_version }} | grep HiveMetaStore | awk '{print $2}' | xargs kill 2>/dev/null
  ignore_errors: true

