##############################
# install uninstall
##############################
- import_tasks: install.yaml
  tags: ['never','install']

- import_tasks: uninstall.yaml
  tags: ['never','uninstall']

##############################
# start stop
##############################
- import_tasks: start.yaml
  tags: ['never','start']

- import_tasks: stop.yaml
  tags: ['never','stop']

##############################
# restart
##############################
- import_tasks: stop.yaml
  tags: ['never','restart']
- import_tasks: start.yaml
  tags: ['never','restart']

##############################
# status
##############################
- import_tasks: status.yaml
  tags: ['never','status']

##############################
# upgrade
##############################
- import_tasks: stop.yaml
  tags: ['never','upgrade']
- import_tasks: install.yaml
  tags: ['never','upgrade']
- import_tasks: start.yaml
  tags: ['never','upgrade']
