- import_tasks: install.yaml
  tags: ['never','install']

- import_tasks: start.yaml
  tags: ['never','start']

- import_tasks: stop.yaml
  tags: ['never','stop']

- import_tasks: uninstall.yaml
  tags: ['never','uninstall']
