- name: start zookeeper
  shell: "if [ -f ~/.bash_profile ]; then source ~/.bash_profile; fi; if [ -f ~/.profile ]; then source ~/.profile; fi; ./zkServer.sh start"
  environment:
    ZK_HOME: "{{ zk_home }}"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ zk_home }}/bin"
  register: result

- name: check zookeeper started status
  async_status:
    jid: "{{ result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 5        # 检查次数为5次, 间隔5秒

- name: recheck zookeeper port
  wait_for:
    port: "{{ zk_client_port }}"
    state: started
    timeout: 10

- name: print zookeeper status
  shell: ". ~/.bash_profile; sleep 2; ./zkServer.sh status"
  environment:
    ZK_HOME: "{{ zk_home }}"
  args:
    executable: /bin/bash
    chdir: "{{ zk_home }}/bin"
  register: result
- debug:
    msg: "{{ result.stdout }}"
