- name: Print zookeeper status
  shell: ". ~/.bash_profile; sleep 2; ./zkServer.sh status"
  environment:
    ZK_HOME: "{{ zk_home }}"
  args:
    executable: /bin/bash
    chdir: "{{ zk_home }}/bin"
  register: result
- debug:
    msg: "{{ result.stdout }}"
