- name: 停止zookeeper
  shell: ". ~/.bash_profile; ./zkServer.sh stop"
  async: 10         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ zk_home }}/bin"
  ignore_errors: true

- name: 等待zookeeper端口的关闭
  wait_for:
    port: "{{ zk_client_port }}"
    state: stopped
    timeout: 10
