- name: 获取要复制的自定义lib列表
  shell: ls
  args:
    chdir: "{{ software_home }}/clib"
  register: list_files
  run_once: true
  delegate_to: localhost

#- name: print lib
#  debug: msg="{{ list_files.stdout_lines }}"

- name: 复制的自定义lib
  copy:
    src: "{{ software_home }}/clib/{{ item }}"
    dest: "{{ flink_home }}/lib"
    force: yes
  with_items: "{{ list_files.stdout_lines|list }}"
