# 安装flink，包括配置文件更新
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]

# 启动flink
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

- import_tasks: start-jh.yaml
  tags: [ 'never', 'start-jh' ]

# 停止flink
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]

- import_tasks: stop-jh.yaml
  tags: [ 'never', 'stop-jh' ]

# 卸载flink
- import_tasks: stop.yaml
  tags: [ 'never', 'uninstall' ]

- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

# 重启flink
- import_tasks: stop.yaml
  tags: [ 'never', 'restart' ]

- import_tasks: start.yaml
  tags: [ 'never', 'restart' ]

# 删除flink日志文件
- import_tasks: clean.yaml
  tags: [ 'never', 'clean' ]
