- name: 启动flink的history server
  shell: ". ~/.bash_profile; ./historyserver.sh start"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ flink_home }}/bin"
  register: result
  run_once: true
  delegate_to: "{{ jobmanager_host }}"

- name: 再确认flink history server的端口
  wait_for:
    port: "{{ historyserver_web_port }}"
    state: started
    timeout: 10
  delegate_to: "{{ jobmanager_host }}"