- name: Get cluster info
  shell: ". ~/.bash_profile; ./bin/redis-cli --cluster info {{ redis_client }} -a {{ redis_password }}"
  async: 30         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ redis_home }}"
  register: v_info
  run_once: true
  when: redis_security_enable == "true"

- name: Get cluster info
  shell: ". ~/.bash_profile; ./bin/redis-cli --cluster info {{ redis_client }}"
  async: 30         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ redis_home }}"
  register: v_info
  run_once: true
  when: redis_security_enable == "false"

- name: Print redis cluster info
  debug:
    msg: "{{ v_info.stdout_lines }}"
