- name: Create cluster redis
  shell: ". ~/.bash_profile; echo -e 'yes\n' | ./bin/redis-cli --cluster create {{ redis_hosts }}"
  async: 30         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ redis_home }}"
  run_once: true
