- name: Create install directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ install_home }}"

- name: Unarchive redis package
  unarchive:
    src: "{{ software_home }}/{{ redis_file }}"
    dest: "{{ install_home }}"
    copy: yes
    creates: "{{ redis_home }}"

- name: Create logs directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ redis_log_dir }}"
  - "{{ redis_config_dir }}"
  - "{{ redis_storage_dir }}"

- name: print redis ports
  debug:
    msg: "redis ports: '{{ redis_ports }}'"

- name: Create property file 'redis.conf'
  template:
    src: "redis.conf-{{ redis_major_version }}.x.j2"
    dest: '{{ redis_config_dir }}/redis-{{ item }}.conf'
  with_items:
  - "{{ redis_ports }}"
