- name: create install directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ install_home }}"

- name: unarchive redis package
  unarchive:
    src: "{{ software_home }}/redis/{{ redis_file }}"
    dest: "{{ install_home }}"
    copy: yes
    creates: "{{ redis_home }}"

- name: create logs directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ redis_log_dir }}"
  - "{{ redis_config_dir }}"
  - "{{ redis_storage_dir }}"

- name: create property file 'redis.conf'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: 'redis.conf-{{ redis_major_version }}.x.j2', dest: '{{ redis_config_dir }}/redis-{{ redis_port }}.conf' }

#- name: write environment variable REDIS_HOME etc
#  lineinfile:
#    dest: ~/.bash_profile
#    state: present
#    line: "{{ item }}"
#  with_items:
#  - 'export REDIS_HOME={{ redis_home }}'
#  - 'export PATH=$REDIS_HOME/bin:$PATH'
