---

- name: Stop the kerberos services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: kerberos_service

- name: Uninstall the kerberos packages
  yum:
    name: ['krb5-libs', 'krb5-server', 'krb5-workstation']
    state: absent