# 实验环境先直接删除了，后面再改成通过改VERSION的方式。
- name: 删除namenode中元数据，datanode中数据文件等
  file: name={{ item }} state=absent
  with_items:
  - "{{ hadoop_tmp_dir }}"

- name: 格式化namenode
  shell: ". ~/.bash_profile; ./hdfs namenode -format"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/bin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"
