- name: 启动namenode
  shell: ". ~/.bash_profile; start-dfs.sh"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_host }}"

#- name: 再确认namenode的端口
#  wait_for:
#    host: "{{ inventory_hostname }}"
#    port: "{{ namenode_port }}"
#    state: started
#    timeout: 20
#  run_once: true
#  delegate_to: "{{ namenode_host }}"

#- name: 启动datanode
#  shell: ". ~/.bash_profile; HADOOP_DATANODE_USER=bduser sudo -E {{ hadoop_home }}/sbin/start-secure-dns.sh"
#  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
#  poll: 2           # 设置为0时, 任务会立即返回
#  args:
#    executable: /bin/bash
#    chdir: "{{ hadoop_home }}/sbin"
#  register: result
#  run_once: true
#  delegate_to: "{{ namenode_host }}"
