- name: 启动job history
  shell: ". ~/.bash_profile; mr-jobhistory-daemon.sh start historyserver"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ yarn_hosts[0] }}"
