- name: 停止namenode
  shell: ". ~/.bash_profile; stop-dfs.sh"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"

- name: 再确认namenode的端口
  wait_for:
    port: "{{ namenode_port }}"
    state: stopped
    timeout: 30
  delegate_to: "{{ namenode_hosts[0] }}"

#- name: 停止datanode
#  shell: ". ~/.bash_profile; HADOOP_DATANODE_USER=bduser sudo -E {{ hadoop_home }}/sbin/stop-secure-dns.sh"
#  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
#  poll: 2           # 设置为0时, 任务会立即返回
#  args:
#    executable: /bin/bash
#    chdir: "{{ hadoop_home }}/sbin"
#  register: result
#  run_once: true
#  delegate_to: "{{ namenode_host }}"
