#  ansible-playbook 02.hadoop.yaml -t uninstall-root -e "ansible_become=true"

- name: 删除安全等相关的文件
  file:
    name: "{{ item }}"
    state: absent
  with_items:
  - "{{ hadoop_container_conf_dir }}"
  - "{{ hadoop_ssl_path }}"
  - "/tmp/keystore"
  - "/tmp/truststore"
  ignore_errors: true
