##########################################################
## Kill HMaster and backup hmaster processes
##########################################################
- name: Get HMaster processes
  shell: ". ~/.bash_profile; ps -ef | grep java | grep -v grep | grep {{ hbase_home }} | grep 'HMaster start' | awk '{print $2}'"
  async: 20
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  register: result
  when: inventory_hostname in master_hosts

- name: Kill HMaster processes
  shell: ". ~/.bash_profile; kill -9 {{ item }}"
  with_items: "{{ result.stdout_lines }}"
  when: inventory_hostname in master_hosts and result.stdout_lines|count > 0

- name: Get backup HMaster processes
  shell: ". ~/.bash_profile; ps -ef | grep java | grep -v grep | grep {{ hbase_home }} | grep 'HMaster --backup start' | awk '{print $2}'"
  async: 20
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  register: result
  when: inventory_hostname in backup_master_hosts

- name: Kill backup HMaster processes
  shell: ". ~/.bash_profile; kill -9 {{ item }}"
  with_items: "{{ result.stdout_lines }}"
  when: inventory_hostname in backup_master_hosts and result.stdout_lines|count > 0

##########################################################
## Kill HRegionServer processes
##########################################################
- name: "Get HRegionServer processes"
  shell: ". ~/.bash_profile; ps -ef | grep java | grep -v grep | grep {{ hbase_home }} | grep 'HRegionServer start' | awk '{print $2}'"
  args:
    executable: /bin/bash
  ignore_errors: true
  register: result
  when: inventory_hostname in regionserver_hosts

- name: Kill HRegionServer processes
  shell: ". ~/.bash_profile; kill -9 {{ item }}"
  with_items: "{{ result.stdout_lines }}"
  when: (inventory_hostname in regionserver_hosts) and (result.stdout_lines|count > 0)

##########################################################
## Check port
##########################################################
- name: Recheck master port
  wait_for:
    port: "{{ item }}"
    state: stopped
    timeout: 20
  with_items:
  - "{{ hbase_master_port }}"
  - "{{ hbase_master_info_port }}"
  when: inventory_hostname in master_hosts or inventory_hostname in backup_master_hosts

- name: Recheck regionserver port
  wait_for:
    port: "{{ item }}"
    state: stopped
    timeout: 20
  with_items:
  - "{{ hbase_regionserver_port }}"
  - "{{ hbase_regionserver_info_port }}"
  when: inventory_hostname in regionserver_hosts
