- name: Copy the krb5 configuration file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "krb5.conf.j2", dest: "/etc/krb5.conf" }

- name: create keytab directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0555
  with_items:
    - "/etc/newland"
    - "/etc/newland/kerberos"

- name: dispatch xxxx.keytab
  copy:
    src: "{{ kerberos_keytab_name }}"
    dest: "/etc/newland/kerberos"
    force: yes
    owner: "{{ install_user }}"
    group: "{{ install_group }}"
    mode: 0444
