- name: Clean data directory
  file:
    path: "{{ item }}"
    owner: "{{ install_user }}"
    state: absent
  with_items:
  - "{{ clickhouse_data_dir }}"

- name: Create data directory
  file:
    name: "{{ item }}"
    owner: "{{ install_user }}"
    state: directory
  with_items:
  - "{{ clickhouse_data_dir }}"
