#- name: Clean log directory
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#  - "{{ clickhouse_log_dir }}"
#
#- name: Create log directory
#  file:
#    name: "{{ item }}"
#    state: directory
#  with_items:
#  - "{{ clickhouse_log_dir }}"

- name: Clean log
  shell: ". ~/.bash_profile; ./clean.sh"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ clickhouse_home }}/bin"