- name: Get ignite pid
  shell: ps -ef | grep ignite | grep java | grep {{ ignite_version }} | grep {{ ignite_home }} | grep -v grep | grep -v VisorConsole | grep -v IgniteJdbcThinDriver | awk '{print $2}'
  register: pid

- name: Kill ignite
  shell: kill -15 {{ pid.stdout }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  when: pid.stdout != ""

- name: "Wait port stopped"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ item }}"
    state: stopped
    timeout: 30
  with_items:
  - "{{ ignite_jdbc_port }}"
  - "{{ ignite_tcp_port }}"
  - "{{ ignite_listener_port }}"
