- name: Get grafana pid
  shell: ps -ef | grep grafana | grep {{ grafana_version }} | grep {{ grafana_home }} | grep -v grep | awk '{print $2}'
  register: pid

- name: Kill grafana
  shell: kill -15 {{ pid.stdout }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  when: pid.stdout != ""

- name: "Wait port {{ grafana_port }} stopped"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ grafana_port }}"
    state: stopped
    timeout: 300
