- hosts: hadoop
  remote_user: "{{ install_user }}"
  become: false
  become_user: root
  gather_facts: yes
  vars:
    ansible_home: "{{ lookup('env', 'PWD') }}"
    vhostfqdn: "{{ hostvars[inventory_hostname].ansible_fqdn }}"
  roles:
  - hadoop
