- hosts: kafka
  remote_user: "{{ install_user }}"
  become_user: "{{ install_user }}"
  gather_facts: yes
  vars:
    vhostipv4: "{{ hostvars[inventory_hostname].ansible_all_ipv4_addresses[0] }}"
  roles:
  - kafka
