- name: Initialize pulsar cluster metadata
  shell: '. ~/.bash_profile; {{ pulsar_home }}/bin/pulsar initialize-cluster-metadata \
          --cluster {{ pulsar_cluster_name }} \
          --zookeeper {{ zookeeper_hosts_first }} \
          --configuration-store {{ zookeeper_hosts_first }} \
          --web-service-url http://{{ broker_hosts_first }}:{{ pulsar_web_port }} \
          --web-service-url-tls https://{{ broker_hosts_first }}:{{ pulsar_web_port_tls }} \
          --broker-service-url pulsar://{{ broker_hosts_first }}:{{ pulsar_broker_port }} \
          --broker-service-url-tls pulsar+ssl://{{ broker_hosts_first }}:{{ pulsar_broker_port_tls }} \
          '
  environment:
    PULSAR_HOME: "{{ pulsar_home }}"
  async: 20
  poll: 2
  args:
    executable: /bin/bash
    chdir: "{{ pulsar_home }}/bin"
  run_once: true

