# ---------------------------------------------
- import_tasks: install.yaml
  tags: ['never','install']

# ---------------------------------------------
#- import_tasks: start.yaml
#  tags: ['never','start']
#- import_tasks: start-standalone.yaml
#  tags: ['never','start-standalone']

## ---------------------------------------------
#- import_tasks: stop.yaml
#  tags: ['never','stop']
#
## ---------------------------------------------
#- import_tasks: stop.yaml
#  tags: ['never','uninstall']
#- import_tasks: delete-topic.yaml
#  tags: ['never','uninstall']
- import_tasks: uninstall.yaml
  tags: ['never','uninstall']

## ---------------------------------------------
#- import_tasks: create-topic.yaml
#  tags: ['never','createtopic']
#
#- import_tasks: delete-topic.yaml
#  tags: ['never','deletetopic']
