- name: Start broker
  shell: '. ~/.bash_profile; {{ item }}'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
    chdir: "{{ pulsar_home }}"
  with_items:
  - "{{ pulsar_home }}/bin/pulsar-daemon start broker"
  register: result

- name: Check broker started status
  async_status:
    jid: "{{ result.results[0].ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 5        # 检查次数为5次, 间隔5秒

- name: Recheck broker port
  wait_for:
    port: "{{ pulsar_broker_port }}"
    state: started
    timeout: 10

- name: List broker cluster
  shell: '. ~/.bash_profile; {{ item }}'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
    chdir: "{{ pulsar_home }}"
  with_items:
  - "{{ pulsar_home }}/bin/pulsar-admin --admin-url http://127.0.0.1:{{ pulsar_web_port }} brokers list pulsar-cluster"
  register: result

- name: Print broker cluster
  debug:
    msg: "{{ result.results[0].stdout_lines|list }}"
