- name: Clean log directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ hbase_log_dir }}"

- name: Create log directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ hbase_log_dir }}"
