- name: Run master and regionserver script
  shell: '. ~/.bash_profile; {{ hbase_home }}/bin/start-hbase.sh'
  async: 20
  poll: 0
  args:
    executable: /bin/bash
    chdir: "{{ hbase_home }}"
  run_once: true
  register: result

- name: Check master and regionserver started status
  async_status:
    jid: "{{ result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
  run_once: true

- name: Recheck master port
  wait_for:
    port: "{{ item }}"
    state: started
    timeout: 10
  with_items:
  - "{{ hbase_master_port }}"
  - "{{ hbase_master_info_port }}"
  when: ansible_hostname in master_hosts

- name: Recheck regionserver port
  wait_for:
    port: "{{ item }}"
    state: started
    timeout: 10
  with_items:
  - "{{ hbase_regionserver_port }}"
  - "{{ hbase_regionserver_info_port }}"
  when: ansible_hostname in regionserver_hosts
