- name: Run mysql script
  shell: '. ~/.bash_profile; export HIVE_HOME={{ hive2_home }}; {{ hive2_home }}/bin/schematool -initSchema -dbType mysql'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
  run_once: true
#  ignore_errors: true
