- name: 'Run metastore and hiveserver2 script'
  shell: '. ~/.bash_profile; {{ item }}'
  environment:
    HIVE_HOME: "{{ hive2_home }}"
  async: 20
  poll: 2
  args:
    executable: /bin/bash
    chdir: "{{ hive2_home }}"
  with_items:
  - "nohup {{ hive2_home }}/bin/hive --service metastore -p {{ hive2_metastore_port }} > {{ hive2_home }}/logs/metastore.log 2>&1 &"
  - "nohup {{ hive2_home }}/bin/hive --service hiveserver2 > {{ hive2_home }}/logs/hiveserver2.log 2>&1 &"

- name: 再确认hive metastore的端口
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ hive2_metastore_port }}"
    state: started
    timeout: 25

- name: 再确认hiveserver2的端口
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ hive2_server2_port }}"
    state: started
    timeout: 60
