# TODO 启动之前要判断一下是否要有进程存在。

- name: get hive metastore pid
  shell: ". ~/.bash_profile; ps -ef | grep java | grep {{ hive2_home }} | grep HiveMetaStore | grep -v grep | awk '{print $2}'"
  environment:
    HIVE_HOME: "{{ hive2_home }}"
  register: pid

- name: kill hive metastore
  shell: kill -9 {{ pid.stdout }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  when: pid.stdout != ""

- name: get hiveserver2 pid
  shell: ". ~/.bash_profile; ps -ef | grep java | grep {{ hive2_home }} | grep HiveServer | grep -v grep | awk '{print $2}'"
  environment:
    HIVE_HOME: "{{ hive2_home }}"
  register: pid

- name: kill hiveserver2
  shell: kill -9 {{ item }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  with_items: "{{ pid.stdout_lines }}"
  ignore_errors: true
  when: pid.stdout != ""

- name: check hive metastore port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ hive2_metastore_port }}"
    state: stopped
    timeout: 10

- name: check hiveserver2 port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ hive2_server2_port }}"
    state: stopped
    timeout: 10
