- name: create install directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ install_home }}"

- name: unarchive kafka package
  unarchive:
    src: "{{ software_home }}/{{ kafka_file }}"
    dest: "{{ install_home }}"
    copy: yes
    creates: "{{ kafka_home }}"

- name: create logs directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ kafka_log_dir }}"

- name: create property file 'server.properties'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: 'conf/server.properties.j2', dest: '{{ kafka_home }}/config/server.properties'}

- name: create customer shell
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
  - { src: 'bin/my-producer.sh.shj2', dest: '{{ kafka_home }}/bin/my-producer.sh'}
  - { src: 'bin/my-consumer.sh.shj2', dest: '{{ kafka_home }}/bin/my-consumer.sh'}
  - { src: 'bin/my-topic.sh.shj2', dest: '{{ kafka_home }}/bin/my-topic.sh'}

- name: write environment variable KAFKA_HOME etc
  lineinfile:
    dest: ~/.bash_profile
    state: present
    line: "{{ item }}"
  with_items:
  - 'export KAFKA_HOME={{ kafka_home }}'
  - 'export PATH=$PATH:$KAFKA_HOME/bin'
