- name: create common property
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'conf/kafka-client-jaas.conf', dest: '{{ kafka_home }}/config/kafka-client-jaas.conf' }
    - { src: 'conf/kafka-server-jaas.conf', dest: '{{ kafka_home }}/config/kafka-server-jaas.conf' }
    - { src: 'conf/producer.properties.j2', dest: '{{ kafka_home }}/config/producer.properties' }
    - { src: 'conf/consumer.properties.j2', dest: '{{ kafka_home }}/config/consumer.properties' }

- name: create plain sasl property
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'conf/producer-plain.properties.j2', dest: '{{ kafka_home }}/config/producer-plain.properties' }
    - { src: 'conf/consumer-plain.properties.j2', dest: '{{ kafka_home }}/config/consumer-plain.properties' }
    - { src: 'conf/command-plain.properties.j2', dest: '{{ kafka_home }}/config/command-plain.properties' }
  when: kafka_sasl_plain_enable|lower == "true"

- name: create plain gssapi property
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'conf/producer-gssapi.properties.j2', dest: '{{ kafka_home }}/config/producer-gssapi.properties' }
    - { src: 'conf/consumer-gssapi.properties.j2', dest: '{{ kafka_home }}/config/consumer-gssapi.properties' }
    - { src: 'conf/command-gssapi.properties.j2', dest: '{{ kafka_home }}/config/command-gssapi.properties' }
  when: kafka_sasl_gssapi_enable|lower == "true"

- name: create executor file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'bin/kafka-consumer-groups.shj2', dest: '{{ kafka_home }}/bin/kafka-consumer-groups.sh' }
    - { src: 'bin/kafka-console-consumer.shj2', dest: '{{ kafka_home }}/bin/kafka-console-consumer.sh' }
    - { src: 'bin/kafka-console-producer.shj2', dest: '{{ kafka_home }}/bin/kafka-console-producer.sh' }
    - { src: 'bin/kafka-server-start.shj2', dest: '{{ kafka_home }}/bin/kafka-server-start.sh' }
