- name: Get prometheus pushgateway pid
  shell: ps -ef | grep pushgateway | grep {{ pgw_port }} | grep -v grep | awk '{print $2}'
  register: pid

- name: Kill prometheus pushgateway
  shell: kill -15 {{ pid.stdout }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  when: pid.stdout != ""

- name: "Wait port {{ pgw_port }} stopped"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ pgw_port }}"
    state: stopped
    timeout: 60
