- name: Clean environment $PROMETHEUS_HOME and so on
  lineinfile:
    dest: ~/.bash_profile
    state: absent
    line: "{{ item }}"
  with_items:
  - 'export PGW_HOME={{ pgw_home }}'
  - 'export PATH=$PATH:PGW_HOME'

- name: Uninstall prometheus pushgateway
  file:
    name: "{{ item }}"
    state: absent
  with_items:
  - "{{ pgw_log_dir }}"
  - "{{ pgw_data_dir }}"
  - "{{ pgw_home }}"
