################################
#### stop journal ##############
################################
- name: stop journalnode(namenode ha)
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh stop journalnode"
  environment:
    HADOOP_HOME: "{{ hadoop_home }}"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  when: inventory_hostname in journal_hosts

- name: Check journalnode port(namenode ha)
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ journal_port }}"
    state: stopped
    timeout: 25
  when: inventory_hostname in journal_hosts

- name: Check journalnode https port(namenode ha)
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ journal_https_port }}"
    state: stopped
    timeout: 25
  when: inventory_hostname in journal_hosts

################################
#### stop namenode #############
################################
- name: Stop master namenode(namenode ha)
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh stop namenode"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"

- name: Check master namenode port(namenode ha)
  wait_for:
    host: "{{ namenode_hosts[0] }}"
    port: "{{ namenode_port }}"
    state: stopped
    timeout: 20
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"

- name: Stop standby namenode(namenode ha)
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh stop namenode"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[1] }}"

- name: Check standby namenode port(namenode ha)
  wait_for:
    host: "{{ namenode_hosts[1] }}"
    port: "{{ namenode_port }}"
    state: stopped
    timeout: 20
  run_once: true
  delegate_to: "{{ namenode_hosts[1] }}"

################################
#### stop zkfc #################
################################
- name: Stop zkfc
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh stop zkfc"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  when: inventory_hostname in namenode_hosts

################################
#### initial ###################
################################
- import_tasks: init-ha.yaml
