################################
#### start namenode(none ha) ###
################################
- name: Start namenode(none ha)
  shell: ". ~/.bash_profile; start-dfs.sh"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"
  when: namenode_ha_enable|lower != "true"

- name: Check namenode port again(none ha)
  wait_for:
    host: "{{ namenode_hosts[0] }}"
    port: "{{ namenode_port }}"
    state: started
    timeout: 1000   # 连接rpc，要等待时间是比较长。
  when: namenode_ha_enable|lower != "true"

################################
#### start master namenode #####
################################
- name: Start master namenode(namenode ha)
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh start namenode"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"
  when: namenode_ha_enable|lower == "true"

- name: Check master namenode port(namenode ha)
  wait_for:
    host: "{{ namenode_hosts[0] }}"
    port: "{{ namenode_port }}"
    state: started
    timeout: 1000   # 连接rpc，要等待时间是比较长。
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"
  when: namenode_ha_enable|lower == "true"

################################
#### start standby namenode ####
################################
- name: Copy namenode from master to standby(namenode ha)
  shell: ". ~/.bash_profile; echo -e 'Y\n' | ./hdfs namenode -bootstrapStandby -force"
  async: 600        # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/bin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[1] }}"
  when: namenode_ha_enable|lower == "true"

- name: Start standby namenode(namenode ha)
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh start namenode"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[1] }}"
  when: namenode_ha_enable|lower == "true"

- name: Check standby namenode port(namenode ha)
  wait_for:
    host: "{{ namenode_hosts[1] }}"
    port: "{{ namenode_port }}"
    state: started
    timeout: 1000   # 连接rpc，要等待时间是比较长。
  run_once: true
  delegate_to: "{{ namenode_hosts[1] }}"
  when: namenode_ha_enable|lower == "true"

#- name: 启动datanode
#  shell: ". ~/.bash_profile; HADOOP_DATANODE_USER=bduser sudo -E {{ hadoop_home }}/sbin/start-secure-dns.sh"
#  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
#  poll: 2           # 设置为0时, 任务会立即返回
#  args:
#    executable: /bin/bash
#    chdir: "{{ hadoop_home }}/sbin"
#  register: result
#  run_once: true
#  delegate_to: "{{ namenode_host }}"
