- name: Stop namenode(none ha)
  shell: ". ~/.bash_profile; stop-dfs.sh"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ namenode_hosts[0] }}"
  when: namenode_ha_enable|lower != "true"

- name: Check namenode port(none ha)
  wait_for:
    host: "{{ namenode_hosts[0] }}"
    port: "{{ namenode_port }}"
    state: stopped
    timeout: 60
  when: namenode_ha_enable|lower != "true"

- name: Stop namenode(ha)
  shell: ". ~/.bash_profile; stop-dfs.sh"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  when: (namenode_ha_enable|lower == "true") and (inventory_hostname in namenode_hosts)

- name: Check namenode port(ha)
  wait_for:
    # host: "{{ namenode_hosts[0] }}"
    port: "{{ namenode_port }}"
    state: stopped
    timeout: 60
  when: (namenode_ha_enable|lower == "true") and (inventory_hostname in namenode_hosts)

#################################
##### stop datanode #############
#################################
- name: Stop datanode(namenode ha)
  shell: ". ~/.bash_profile; ./hadoop-daemon.sh stop datanode"
  async: 120        # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  when: namenode_ha_enable|lower == "true"

#- name: 停止datanode
#  shell: ". ~/.bash_profile; HADOOP_DATANODE_USER=bduser sudo -E {{ hadoop_home }}/sbin/stop-secure-dns.sh"
#  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
#  poll: 2           # 设置为0时, 任务会立即返回
#  args:
#    executable: /bin/bash
#    chdir: "{{ hadoop_home }}/sbin"
#  register: result
#  run_once: true
#  delegate_to: "{{ namenode_host }}"
