- name: Test Dataname
  debug:
    msg: "{{ datanode_hosts }}"

- name: Test Namenode
  debug:
    msg: "{{ namenode_hosts }}"

- name: delete datanode directory for namenode format
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ hadoop_datanode_dir }}/in_use.lock"
  - "{{ hadoop_datanode_dir }}"
