# ---------------------------------------------
# install and uninstall
# ---------------------------------------------
- import_tasks: install.yaml
  tags: [ 'never','install' ]

- import_tasks: stop.yaml
  tags: [ 'never','uninstall' ]
- import_tasks: uninstall.yaml
  tags: [ 'never','uninstall' ]

# ---------------------------------------------
# start and stop
# ---------------------------------------------
- import_tasks: start.yaml
  tags: [ 'never','start' ]

- import_tasks: stop.yaml
  tags: [ 'never','stop' ]

# ---------------------------------------------
# restart
# ---------------------------------------------
- import_tasks: stop.yaml
  tags: [ 'never','restart' ]
- import_tasks: start.yaml
  tags: [ 'never','restart' ]

# ---------------------------------------------
# upgrade
# ---------------------------------------------
- import_tasks: stop.yaml
  tags: [ 'never','upgrade' ]
- import_tasks: install.yaml
  tags: [ 'never','upgrade' ]
- import_tasks: start.yaml
  tags: [ 'never','upgrade' ]
