- name: Start nacos
  shell: '. ~/.bash_profile; {{ nacos_home }}/bin/startup.sh'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
    chdir: "{{ nacos_home }}"
  register: result

- name: Check nacos started status
  async_status:
    jid: "{{ result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 5        # 检查次数为5次, 间隔5秒

- name: Recheck nacos port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ nacos_port }}"
    state: started
    timeout: 20
