- name: Stop nacos
  shell: ". ~/.bash_profile; ./shutdown.sh"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ nacos_home }}/bin"
  ignore_errors: true

- name: Check nacos port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ nacos_port }}"
    state: stopped
    timeout: 10
