- name: Stop the kerberos services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ kerberos_services }}"

- name: Delete kerberos database
  file:
    name: "/var/kerberos/{{ item }}"
    state: absent
  with_items:
  - "db_created"
  - "admin_created"
  - "krb5kdc/principal"
  - "krb5kdc/principal.kadm5"
  - "krb5kdc/principal.kadm5.lock"
  - "krb5kdc/principal.ok"
