---

- name: Add the OS specific varibles
  include_vars: "main.yaml"

- name: Install the kerberos packages
  yum:
    name: ['krb5-libs', 'krb5-server', 'krb5-workstation']
    # name: "{{ kerberos_server_redhat_package }}"
    state: present

- name: Copy the kdc configuration file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: "kdc.conf.j2", dest: "/var/kerberos/krb5kdc/kdc.conf" }
  - { src: "kadm5.acl.j2", dest: "/var/kerberos/krb5kdc/kadm5.acl" }
  - { src: "krb5.conf.j2", dest: "/etc/krb5.conf" }
