---

- name: list principals
  shell: 'kadmin.local -q "list_principals"'
  async: 20
  poll: 2
  args:
    executable: /bin/bash
    chdir: "/root"
  register: result

- name: show list principal
  debug:
    msg: "{{ result.stdout_lines }}"
    verbosity: 0