# 安装kerberos服务端
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]

# --------------------------------------------------
# 卸载kerberos服务端
- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

# --------------------------------------------------
# 创建kerberos的数据库，以有管理员账号
- import_tasks: create-db.yaml
  tags: [ 'never', 'create-db' ]

# 删除kerberos的数据库，以有管理员账号
- import_tasks: destroy-db.yaml
  tags: [ 'never', 'destroy-db' ]

# --------------------------------------------------
# 启动kerberos服务端
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

# --------------------------------------------------
# 停止kerberos服务端
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]

# --------------------------------------------------
# 重启kerberos服务端
- import_tasks: restart.yaml
  tags: [ 'never', 'restart' ]

# --------------------------------------------------
# create keytab
- import_tasks: create-keytab.yaml
  tags: [ 'never', 'create-keytab' ]

# --------------------------------------------------
# create principal
- import_tasks: create-princ.yaml
  tags: [ 'never', 'create-princ' ]

- import_tasks: list-princ.yaml
  tags: [ 'never', 'list-princ' ]

- import_tasks: delete-princ.yaml
  tags: [ 'never', 'delete-princ' ]
