- name: Create install directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ install_home }}"

- name: Unarchive kafka package
  unarchive:
    src: "{{ software_home }}/{{ kafka_file }}"
    dest: "{{ install_home }}"
    copy: yes
    creates: "{{ kafka_home }}"

- name: Create data and log directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ kafka_log_dir }}"
  - "{{ kafka_data_dir.split(',')|list }}"

- name: Create property file 'server.properties'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: 'conf/server-{{ kafka_major_version }}.properties.j2', dest: '{{ kafka_home }}/config/kraft/server.properties'}
  - { src: 'conf/tools-log4j.properties', dest: '{{ kafka_home }}/config/tools-log4j.properties'}

- name: Create customer shell
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
  - { src: 'bin/sproducer.sh.shj2', dest: '{{ kafka_home }}/bin/sproducer.sh'}
  - { src: 'bin/sconsumer.sh.shj2', dest: '{{ kafka_home }}/bin/sconsumer.sh'}
  - { src: 'bin/stopics.sh.shj2', dest: '{{ kafka_home }}/bin/stopics.sh'}
  - { src: 'bin/kafka-server-stop.sh.shj2', dest: '{{ kafka_home }}/bin/kafka-server-stop.sh' }

## 当需要鉴权时，需要安装ssl客户端的配置文件
#- import_tasks: install-ssl-client.yaml
#  when: kafka_ssl_enable|lower == "true"

# 当需要SASL
- import_tasks: install-sasl-client.yaml
  when: kafka_sasl_plain_enable|lower == "true" or kafka_sasl_gssapi_enable|lower == "true"
