# 删除操作系统最大进程数和最大文件打开数限制的修改, /etc/security/limits.conf
- block:
  - name: 删除limits.conf文件数
    lineinfile:
      dest: /etc/security/limits.conf
      regexp: "{{ item }}"
      state: absent
    with_items:
    - '\{{ install_user }}\tsoft\tnofile\t[0-9]+'
    - '\{{ install_user }}\thard\tnofile\t[0-9]+'
    - '\{{ install_user }}\tsoft\tnproc\t[0-9]+'
    - '\{{ install_user }}\thard\tnproc\t[0-9]+'
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "SLES"
    - handle_ulimit == "yes"

# 删除内核参数, /etc/sysctl.conf
- block:
  - name: 删除sysctl.conf中设置内核参数
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: absent
    with_items:
    - { name: 'vm.swappiness', value: 0 }
    - { name: 'net.core.somaxconn', value: 20000 }
    - { name: 'net.ipv4.ip_local_port_range', value: "1024 65000" }
    - { name: 'net.ipv4.tcp_keepalive_probes', value: 5 }
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: 15 }
    - { name: 'net.ipv4.tcp_keepalive_time', value: 1200 }
    - { name: 'net.ipv4.tcp_tw_reuse', value: 1 }
    - { name: 'net.ipv4.tcp_tw_recycle', value: 1 }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: 5000 }
    - { name: 'net.ipv4.tcp_fin_timeout', value: 30 }
    - { name: 'net.ipv4.tcp_syn_retries', value: 3 }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: 8192 }
    - { name: 'net.core.rmem_default', value: 8388608 }
    - { name: 'net.core.rmem_max', value: 16777216 }
    - { name: 'net.core.wmem_default', value: 8388608 }
    - { name: 'net.core.wmem_max', value: 16777216 }
    - { name: 'net.ipv4.tcp_rmem', value: "4096 87380 16777216" }
    - { name: 'net.ipv4.tcp_wmem', value: "4096 87380 16777216" }
    tags:
    - set sysctl
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "SLES"
    - handle_linux_core == "yes"
