# 安装etcd
- import_tasks: install.yaml
  tags: ['never','install']

# 启动etcd
- import_tasks: start.yaml
  tags: ['never','start']

# 停止etcd
- import_tasks: stop.yaml
  tags: ['never','stop']

# 卸载etcd
- import_tasks: uninstall.yaml
  tags: ['never','uninstall']

# 重启etcd
- import_tasks: stop.yaml
  tags: ['never','restart']
- import_tasks: start.yaml
  tags: ['never','restart']

# 压缩与碎片整理etcd
- import_tasks: compact.yaml
  tags: ['never','compact']

# 碎片整理etcd
- import_tasks: defrag.yaml
  tags: ['never','defrag']

# 获取etcd状态
- import_tasks: status.yaml
  tags: ['never','status']

# 获取etcd快照
# - import_tasks: snapshot.yaml
#   tags: ['never','snapshot']

# 恢复etcd快照
# - import_tasks: restore.yaml
#   tags: ['never','restore']

# 升级etcd
- import_tasks: stop.yaml
  tags: ['never','upgrade']
- import_tasks: install.yaml
  tags: ['never','upgrade']
- import_tasks: start.yaml
  tags: ['never','upgrade']

# 告警展示
- import_tasks: alarm.yaml
  tags: ['never','alarm']

# 告警展示
- import_tasks: clean.yaml
  tags: ['never','clean']
