- name: generate snapshot
  shell: ". ~/.bash_profile; ./handle-etcd.sh snapshot >> run.log 2>&1 &"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ etcd_home }}"
  run_once: true

- name: fetch snapshot
  fetch:
    src: "{{ etcd_snapshot_home }}/snapshot.db"
    dest: "{{ software_home }}/snapshot/snapshot.db"
    flat: true
    fail_on_missing: true
  run_once: true
