- name: 启动etcd
  shell: ". ~/.bash_profile; ./handle-etcd.sh start > run.log 2>&1 &"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ etcd_home }}"

- name: "等待端口{{ etcd_port }}是否打开"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ etcd_port }}"
    state: started
    timeout: 20
