- name: 获取etcd的状态
  shell: ". ~/.bash_profile; etcdctl --endpoints={{ etcd_endpoints }} endpoint status -w table"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ etcd_home }}"
  register: statusResult

- name: 获取etcd的健康状况
  shell: ". ~/.bash_profile; etcdctl --endpoints={{ etcd_endpoints }} endpoint health"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ etcd_home }}"
  register: healthResult

- name: Print etcd status
  debug: msg="{{ statusResult.stdout_lines }}"

- name: Print etcd health
  debug: msg="{{ healthResult.stdout_lines }}"
