# ansible-playbook 02.hadoop.yaml -t install-cgroup -e "ansible_become=true"

- name: 生成控制组
  shell: ". ~/.bash_profile; cgcreate -g cpu,cpuset,memory:{{ yarn_cgroup_hierarchy }}"
  args:
    executable: /bin/bash
    chdir: "~/"
    creates: "{{ yarn_cgroup_mount_path }}/cpu{{ yarn_cgroup_hierarchy }}"

- name: 修改控制组中子系统文件的属组
  shell: ". ~/.bash_profile; chown -R {{ yarn_lce_user }}:{{ yarn_lce_group }} {{ yarn_cgroup_mount_path }}{{ item }}{{ yarn_cgroup_hierarchy }}"
  args:
    executable: /bin/bash
    chdir: "~/"
  with_items:
  - "/cpu"
  - "/cpuset"
  - "/memory"
