- name: 停止job history
  shell: ". ~/.bash_profile; mr-jobhistory-daemon.sh stop historyserver"
  async: 60         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: result
  run_once: true
  delegate_to: "{{ jobhistory_host }}"

- debug:
    msg: "{{ result.stdout }}"

- name: 再确认job history的端口
  wait_for:
    host: "{{ jobhistory_host }}"
    port: "{{ jobhistory_port }}"
    state: stopped
    timeout: 30
  run_once: true
  delegate_to: "{{ jobhistory_host }}"
