- name: Create the installation directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ install_home }}"

- name: Unarchive hbase package
  unarchive:
    src: "{{ software_home }}/{{ hbase_file }}"
    dest: "{{ install_home }}"
    copy: yes
    creates: "{{ hbase_home }}"

- name: Create the installation directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ hbase_home }}/exec"
  - "{{ hbase_home }}/downloadedresources"
  - "{{ hbase_log_dir }}"
  - "{{ hbase_zookeeper_data_dir }}"

- name: Create hbase configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: 'conf/hbase-env.shj2', dest: '{{ hbase_conf_dir }}/hbase-env.sh' }
  - { src: 'conf/hbase-site.xmlj2', dest: '{{ hbase_conf_dir }}/hbase-site.xml' }
  - { src: 'host/backup-masters.j2', dest: '{{ hbase_conf_dir }}/backup-masters' }
  - { src: 'host/regionservers.j2', dest: '{{ hbase_conf_dir }}/regionservers' }
  - { src: 'conf/core-site.xml', dest: '{{ hbase_conf_dir }}/core-site.xml' }
  - { src: 'conf/hdfs-site.xml', dest: '{{ hbase_conf_dir }}/hdfs-site.xml' }
#   - { src: 'hbase-log4j.properties.j2', dest: '{{ hbase_conf_dir }}/hbase-log4j.properties' }

- name: Delete redundant file
  file:
    path: "{{ hbase_home }}/{{ item }}"
    state: absent
  with_items:
  - CHANGES.md
  - LEGAL
  - LICENSE.txt
  - NOTICE.txt
  - README.txt
  - RELEASENOTES.md

- name: Copy htrace-core-3.1.0-incubating.jar
  copy:
    src: "{{ hbase_home }}/lib/client-facing-thirdparty/htrace-core-3.1.0-incubating.jar"
    dest: "{{ hbase_home }}/lib"
    force: yes
    remote_src: true

#- name: Write the environment variable $HADOOP_HOME, and so on
#  lineinfile:
#    dest: ~/.bash_profile
#    state: present
#    line: "{{ item }}"
#  with_items:
#  - 'export HBASE_HOME={{ hbase_home }}'
#  - 'export PATH=$PATH:$HBASE_HOME/bin'

- name: Check master count
  fail:
    msg: "Master count should be bigger then 0"
  when: master_count == 0

- name: Check regionserver count
  fail:
    msg: "Regionserver count should be bigger then 0"
  when: regionserver_count == 0
