# 删除server keystore, client keystore
- name: Delete server keystore, client keystore
  file:
    path: "{{ ssl_path }}/{{ item }}"
    state: absent
  with_items:
  - "{{ ssl_server_ks }}"
  - "{{ ssl_client_ks }}"
