#################################
# install and uninstall hbase
#################################
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]
- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

#################################
# start stop clean
#################################
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]
- import_tasks: stop-force.yaml
  tags: [ 'never', 'stop-force' ]
- import_tasks: clean.yaml
  tags: [ 'never', 'clean' ]
- import_tasks: clean-data.yaml
  tags: [ 'never', 'clean-data' ]

#################################
# restart hbase
#################################
- import_tasks: stop.yaml
  tags: [ 'never', 'restart' ]
- import_tasks: start.yaml
  tags: [ 'never', 'restart' ]

#################################
# upgrade hbase
#################################
- import_tasks: stop.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: install.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: start.yaml
  tags: [ 'never', 'upgrade' ]

