# install prometheus export
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]

# uninstall prometheus export
- import_tasks: stop.yaml
  tags: [ 'never', 'uninstall' ]
- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

# start prometheus export
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

# stop prometheus export
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]

# restart prometheus export
- import_tasks: restart.yaml
  tags: [ 'never', 'restart' ]

# upgrade prometheus export
- import_tasks: install.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: restart.yaml
  tags: [ 'never', 'upgrade' ]

# clean prometheus export log
- import_tasks: clean.yaml
  tags: [ 'never', 'clean' ]
