- name: Get prometheus node exporter pid
  shell: ps -ef | grep node_exporter | grep {{ pne_port }} | grep -v grep | awk '{print $2}'
  register: pid

- name: Kill prometheus node exporter
  shell: kill -15 {{ pid.stdout }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  when: pid.stdout != ""

- name: "Wait port {{ pne_port }} stopped"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ pne_port }}"
    state: stopped
    timeout: 300
