# 安装前的检查
- import_tasks: install-common.yaml

- name: Create prometheus configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
  - { src: 'conf/prometheus-center.yml.j2', dest: '{{ prom_home }}/prometheus.yml', mode: "0644" }
