# install prometheus
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]
- import_tasks: install-center.yaml
  tags: [ 'never', 'install-center' ]

# uninstall prometheus
- import_tasks: stop.yaml
  tags: [ 'never', 'uninstall' ]
- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

# start prometheus
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

# stop prometheus
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]

# restart prometheus
- import_tasks: restart.yaml
  tags: [ 'never', 'restart' ]

# upgrade prometheus
- import_tasks: install.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: restart.yaml
  tags: [ 'never', 'upgrade' ]

# upgrade prometheus centre
- import_tasks: install-center.yaml
  tags: [ 'never', 'upgrade-center' ]
- import_tasks: restart.yaml
  tags: [ 'never', 'upgrade-center' ]

# clean prometheus log
- import_tasks: clean.yaml
  tags: [ 'never', 'clean' ]

# reload prometheus log
- import_tasks: reload.yaml
  tags: [ 'never', 'reload' ]
