- name: Run prometheus
  shell: '. ~/.bash_profile; nohup ./startup.sh >{{ prom_log_dir }}/prometheus.log 2>&1 &'
  async: 30
  poll: 5
  args:
    executable: /bin/bash
    chdir: "{{ prom_home }}"

- name: "Wait port {{ prom_port }} opened"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ prom_port }}"
    state: started
    timeout: 60
