- name: Get prometheus pid
  shell: ps -ef | grep prometheus | grep {{ prom_version }} | grep {{ prom_port }} | grep -v grep | awk '{print $2}'
  register: pid

- name: Kill prometheus
  shell: kill -15 {{ pid.stdout }}
  async: 30
  poll: 2
  args:
    executable: /bin/bash
  ignore_errors: true
  when: pid.stdout != ""

- name: "Wait port {{ prom_port }} stopped"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ prom_port }}"
    state: stopped
    timeout: 300
