- name: Create the installation directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ install_home }}"

- name: Create the installation directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ minio_home }}"
  - "{{ minio_data_dirs.split(',')|list }}"

- name: Write the environment variable $MINIO_HOME, and so on
  lineinfile:
    dest: ~/.bash_profile
    state: present
    line: "{{ item }}"
  with_items:
  - "export MINIO_HOME={{ minio_home }}"
  - "export PATH=$MINIO_HOME:$PATH"
  - "export MINIO_REGION_NAME='中国华北一区'"

- name: Copy minio software
  copy:
    src: "{{ software_home }}/minio/{{ item.src }}"
    mode: 0744
    dest: "{{ minio_home }}"
    force: yes
  with_items:
  - { src: "minio" }
  - { src: "mc" }

- name: Copy handle-cluster.sh
  template:
    dest: "{{ minio_home }}/handle-cluster.sh"
    mode: 0744
    src: handle-cluster.sh.j2sh
