- name: stop minio
  shell: ". ~/.bash_profile; nohup {{ etcd_home }}/handle-minio.sh stop > {{ minio_home }}/run.log 2>&1 &"
  ignore_errors: true

- name: Delete minio directory and data directory
  file: path={{ item }} state=absent
  with_items:
  - "{{ minio_home }}"
  - "{{ minio_data_dir }}"

- name: clean environment $MINIO_HOME and so on
  lineinfile:
    dest: ~/.bash_profile
    state: absent
    line: "{{ item }}"
  with_items:
  - "export MINIO_HOME={{ minio_home }}"
  - "export PATH=$MINIO_HOME:$PATH"
  - "export MINIO_REGION_NAME='中国华北一区'"
