# install elasticsearch
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]

# uninstall elasticsearch
- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

# start elasticsearch
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

# stop elasticsearch
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]

# restart elasticsearch
- import_tasks: restart.yaml
  tags: [ 'never', 'restart' ]

# clean elasticsearch log
- import_tasks: clean.yaml
  tags: [ 'never', 'clean' ]
