- name: Create the installation directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ install_home }}"

- name: unarchive hive package
  unarchive:
    src: "{{ software_home }}/{{ hive3_file }}"
    dest: "{{ install_home }}"
    copy: yes
    creates: "{{ hive3_home }}"

- name: Create the installation directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ hive3_local_scratchdir }}"
  - "{{ hive3_local_tmp_dir }}"
  - "{{ hive3_home }}/logs"
  - "{{ hive3_home }}/exec"
  - "{{ hive3_home }}/downloadedresources"

- name: copy mysql-connector-java-5.1.x.jar
  copy:
    src: "mysql-connector-java-5.1.47.jar"
    dest: "{{ hive3_home }}/lib/mysql-connector-java.jar"
    force: yes

- name: create hive configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: 'hive-env-{{ hive3_version }}.sh.shj2', dest: '{{ hive3_conf_dir }}/hive-env.sh' }
  - { src: 'hive-site-{{ hive3_version }}.xml.xj2', dest: '{{ hive3_conf_dir }}/hive-site.xml' }
  - { src: 'hive-log4j2.properties.j2', dest: '{{ hive3_conf_dir }}/hive-log4j2.properties' }

#- name: Write the environment variable $HADOOP_HOME, and so on
#  lineinfile:
#    dest: ~/.bash_profile
#    state: present
#    line: "{{ item }}"
#  with_items:
#  - 'export HIVE_HOME={{ hive2_home }}'
#  - 'export PATH=$PATH:$HIVE_HOME/bin'

