# install hive
- import_tasks: install.yaml
  tags: [ 'never', 'install' ]

# start hive
- import_tasks: start.yaml
  tags: [ 'never', 'start' ]

# stop hive
- import_tasks: stop.yaml
  tags: [ 'never', 'stop' ]

# restart hive
- import_tasks: stop.yaml
  tags: [ 'never', 'restart' ]
- import_tasks: clean.yaml
  tags: [ 'never', 'restart' ]
- import_tasks: start.yaml
  tags: [ 'never', 'restart' ]

# upgrade hive
- import_tasks: stop.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: clean.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: install.yaml
  tags: [ 'never', 'upgrade' ]
- import_tasks: start.yaml
  tags: [ 'never', 'upgrade' ]

# init hive
- import_tasks: init.yaml
  tags: [ 'never', 'init' ]

# get status
- import_tasks: status.yaml
  tags: [ 'never', 'status' ]

# clean log
- import_tasks: clean.yaml
  tags: [ 'never', 'clean' ]
