vhostipv4: "{{ hostvars[inventory_hostname].ansible_all_ipv4_addresses[0] }}"
vhostipv6: "{{ hostvars[inventory_hostname].ansible_all_ipv6_addresses[0] }}"
vhostname: "{{ hostvars[inventory_hostname].ansible_hostname }}"
vhostfqdn: "{{ hostvars[inventory_hostname].ansible_fqdn }}"