- name: Clean logs
  shell: ". ~/.bash_profile; rm -fr {{ spark2_logs_dir }}/*"
  async: 120        # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是15秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ spark2_home }}/bin"
