- name: Stop spark2.x all
  shell: ". ~/.bash_profile; ./stop-all.sh"
  environment:
    SPARK_HOME: "{{ spark2_home }}"
  async: 20         # 最大超时时间以及轮询其状态的频率, 如果你没有为poll指定值, 那么默认的轮询频率是20秒钟
  poll: 2           # 设置为0时, 任务会立即返回
  args:
    executable: /bin/bash
    chdir: "{{ spark2_home }}/sbin"
  ignore_errors: true

#- name: Check zookeeper port
#  wait_for:
#    port: "{{ zk_client_port }}"
#    state: stopped
#    timeout: 10
